client_id = "a65a870080a10442e6db61e4a2d5fdcf"
name = "customer-orders-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "write_app_proxy,read_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "/proxy"
prefix = "apps"
subpath = "customer-data"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders-create"